import * as THREE from 'three';
import {createGeodesicGraph,PIECES,SPECIAL_PIECE,rotatedPiece,validateCandidate} from './orbital-core.js';
import './orbital.css';

const canvas=document.querySelector('#viewport'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,100);camera.position.set(0,0,4.2);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0xa5eee5,0x10141c,2.1));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(3,4,5);scene.add(key);
const planet=new THREE.Group();scene.add(planet);planet.add(new THREE.Mesh(new THREE.SphereGeometry(1.08,64,40),new THREE.MeshStandardMaterial({color:0x101b22,roughness:.9,metalness:.18})));
const graph=createGeodesicGraph(2),cellMeshes=[],radius=1.115,plateRadius=.105;
const palette={empty:0x53656b,pentagon:0xa26d2b,occupied:0xb8c6c8,valid:0x70f3df,invalid:0xff4d55,special:0xffd76e};
const dropNormal=graph.cells[53].normal.clone(),dropU=new THREE.Vector3(1,0,0).addScaledVector(dropNormal,-dropNormal.x).normalize(),dropV=new THREE.Vector3().crossVectors(dropNormal,dropU).normalize(),orbitalDistance=1.82;
for(const cell of graph.cells){const geometry=new THREE.CircleGeometry(plateRadius,cell.cellType==='PENTAGON'?5:6);geometry.rotateZ(Math.PI/6);const material=new THREE.MeshStandardMaterial({color:cell.cellType==='PENTAGON'?palette.pentagon:palette.empty,roughness:.66,metalness:.38,emissive:0x000000,emissiveIntensity:.8,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geometry,material);mesh.position.copy(cell.normal).multiplyScalar(radius);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),cell.normal);mesh.userData.cell=cell;planet.add(mesh);cellMeshes.push(mesh);}

const neighborPoints=[];for(const cell of graph.cells)for(const id of cell.neighbors)if(cell.id<id)neighborPoints.push(cell.center.clone().multiplyScalar(1.09),graph.cells[id].center.clone().multiplyScalar(1.09));const debugLinks=new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(neighborPoints),new THREE.LineBasicMaterial({color:0x36c8b4,transparent:true,opacity:.2}));debugLinks.visible=false;planet.add(debugLinks);

const orbitalGroup=new THREE.Group();scene.add(orbitalGroup);const pieceMaterial=new THREE.MeshStandardMaterial({color:0xe4eff1,emissive:0x8aaeb5,emissiveIntensity:1.3,metalness:.65,roughness:.28}),pieceMeshes=[];
const laserGeometry=new THREE.BufferGeometry().setFromPoints([dropNormal.clone().multiplyScalar(2.3),dropNormal.clone().multiplyScalar(1.12)]),laser=new THREE.Line(laserGeometry,new THREE.LineBasicMaterial({color:0xff323c,transparent:true,opacity:.9}));scene.add(laser);
const aimRing=new THREE.Mesh(new THREE.RingGeometry(.12,.135,48),new THREE.MeshBasicMaterial({color:0xff424a,transparent:true,opacity:.8,side:THREE.DoubleSide}));aimRing.position.z=1.13;scene.add(aimRing);
aimRing.position.copy(dropNormal).multiplyScalar(1.13);aimRing.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),dropNormal);

let rotationIndex=0,pieceCounter=0,placedCount=0,socketsFilled=0,state='AIMING',candidate={targetIds:[],result:{valid:false,reason:'SPAWNING'}},debug=false;
let bag=[...PIECES],currentPiece=drawPiece(),nextPiece=drawPiece();
function drawPiece(){if(pieceCounter>0&&pieceCounter%7===0)return{...SPECIAL_PIECE,cells:SPECIAL_PIECE.cells.map(x=>[...x])};if(!bag.length)bag=[...PIECES].sort(()=>Math.random()-.5);const p=bag.shift();return{...p,cells:p.cells.map(x=>[...x])};}
function axialToPlane([q,r]){const spacing=.27;return new THREE.Vector2(Math.sqrt(3)*(q+r*.5)*spacing,1.5*r*spacing);}
function rebuildOrbitalPiece(){for(const mesh of pieceMeshes)orbitalGroup.remove(mesh);pieceMeshes.length=0;const cells=rotatedPiece(currentPiece,rotationIndex);for(const axial of cells){const p=axialToPlane(axial),g=new THREE.CircleGeometry(.095,currentPiece.special?5:6);g.rotateZ(Math.PI/6);const mesh=new THREE.Mesh(g,pieceMaterial.clone());mesh.material.color.set(currentPiece.special?0xffd979:0xddecef);mesh.material.emissive.set(currentPiece.special?0xff9b27:0x739da4);mesh.position.copy(dropNormal).multiplyScalar(orbitalDistance).addScaledVector(dropU,p.x).addScaledVector(dropV,p.y);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),dropNormal);orbitalGroup.add(mesh);pieceMeshes.push(mesh);}updateHud();}
function closestCell(localDirection){let best=-1,bestDot=-Infinity;for(const cell of graph.cells){const dot=localDirection.dot(cell.normal);if(dot>bestDot){bestDot=dot;best=cell.id;}}return best;}
function solveProjection(){const inverse=planet.quaternion.clone().invert(),pieceCells=rotatedPiece(currentPiece,rotationIndex),targetIds=[];for(const axial of pieceCells){const p=axialToPlane(axial),worldPoint=dropNormal.clone().multiplyScalar(orbitalDistance).addScaledVector(dropU,p.x).addScaledVector(dropV,p.y),hitDirection=worldPoint.normalize().applyQuaternion(inverse);targetIds.push(closestCell(hitDirection));}const logical={...currentPiece,cells:pieceCells},result=validateCandidate(graph,logical,targetIds);candidate={targetIds,result};return candidate;}
function resetCellMaterials(){for(const mesh of cellMeshes){const cell=mesh.userData.cell,base=cell.occupied?palette.occupied:cell.cellType==='PENTAGON'?palette.pentagon:palette.empty;mesh.material.color.set(base);mesh.material.emissive.set(0x000000);mesh.scale.setScalar(cell.occupied?1.04:1);}}
function renderPreview(){resetCellMaterials();const color=candidate.result.valid?(candidate.result.reason==='SPECIAL_MATCH'?palette.special:palette.valid):palette.invalid;for(const id of candidate.targetIds){const mesh=cellMeshes[id];mesh.material.color.set(color);mesh.material.emissive.set(color);mesh.material.emissiveIntensity=.65;mesh.scale.setScalar(1.12);}laser.material.color.set(candidate.result.valid?0xff3844:0xff101b);aimRing.material.color.set(candidate.result.valid?0x71f6e1:0xff303c);}
function rotatePiece(delta){if(state!=='AIMING')return;rotationIndex=(rotationIndex+delta+6)%6;rebuildOrbitalPiece();}
function commitDrop(){if(state!=='AIMING'||!candidate.result.valid){flashStatus(candidate.result.reason,true);return;}state='IMPACT';for(const id of candidate.targetIds){const cell=graph.cells[id];cell.occupied=true;cell.occupantId=pieceCounter;if(cell.cellType==='PENTAGON')socketsFilled++;}placedCount++;pieceCounter++;flashStatus(currentPiece.special?'SOCKET CORE LOCKED':'PAYLOAD COMMITTED',false,currentPiece.special);setTimeout(()=>{currentPiece=nextPiece;nextPiece=drawPiece();rotationIndex=0;state='AIMING';rebuildOrbitalPiece();},260);}
function restart(){for(const cell of graph.cells){cell.occupied=false;cell.occupantId=-1;}pieceCounter=placedCount=socketsFilled=rotationIndex=0;bag=[...PIECES];currentPiece=drawPiece();nextPiece=drawPiece();state='AIMING';planet.quaternion.identity();rebuildOrbitalPiece();}
function flashStatus(text,invalid=false,special=false){const el=document.querySelector('#status');el.textContent=text.replaceAll('_',' ');el.className=`status${invalid?' invalid':special?' special':''}`;}
function updateHud(){document.querySelector('#current-piece').textContent=currentPiece.name;document.querySelector('#next-piece').textContent=nextPiece.name;document.querySelector('#placed').textContent=placedCount;document.querySelector('#sockets').textContent=`${socketsFilled} / 12`;const s=graph.cells.filter(c=>c.cellType==='PENTAGON').length;document.querySelector('#telemetry-grid').innerHTML=[['Graph cells',graph.cells.length],['Hex nodes',graph.cells.length-s],['Pentagon nodes',s],['Graph source','ICOSPHERE DUAL'],['Piece turn',`${rotationIndex*60}°`],['Candidate',candidate.targetIds.join(', ')],['Validation',candidate.result.reason]].map(x=>`<span>${x[0]}</span><span>${x[1]}</span>`).join('');flashStatus(candidate.result.reason,!candidate.result.valid,candidate.result.reason==='SPECIAL_MATCH');}

const keys=new Set();addEventListener('keydown',e=>{keys.add(e.code);if(e.repeat)return;if(e.code==='KeyZ')rotatePiece(-1);if(e.code==='KeyX')rotatePiece(1);if(e.code==='Space'){e.preventDefault();commitDrop();}if(e.code==='KeyR')restart();if(e.code==='F1'){e.preventDefault();debug=!debug;debugLinks.visible=debug;}});addEventListener('keyup',e=>keys.delete(e.code));
let dragging=false,lastX=0,lastY=0;canvas.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging||state!=='AIMING')return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;const qx=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),dx*.006),qy=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),dy*.006);planet.quaternion.premultiply(qx).premultiply(qy).normalize();});canvas.addEventListener('pointerup',()=>dragging=false);
document.querySelector('#rotate-left').onclick=()=>rotatePiece(-1);document.querySelector('#drop').onclick=commitDrop;document.querySelector('#restart').onclick=restart;
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
rebuildOrbitalPiece();let last=performance.now();renderer.setAnimationLoop(now=>{const dt=Math.min((now-last)/1000,.05);last=now;if(state==='AIMING'){const speed=.85*dt;if(keys.has('KeyA'))planet.rotateOnWorldAxis(new THREE.Vector3(0,1,0),-speed);if(keys.has('KeyD'))planet.rotateOnWorldAxis(new THREE.Vector3(0,1,0),speed);if(keys.has('KeyW'))planet.rotateOnWorldAxis(new THREE.Vector3(1,0,0),-speed);if(keys.has('KeyS'))planet.rotateOnWorldAxis(new THREE.Vector3(1,0,0),speed);planet.quaternion.normalize();}solveProjection();renderPreview();updateHud();renderer.render(scene,camera);});
